/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Phone = IDL.Text;
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'phone' : Phone,
});
export const WithdrawalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const WithdrawalRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : WithdrawalStatus,
  'bankAccountId' : IDL.Nat,
  'createdAt' : IDL.Int,
  'user' : IDL.Principal,
  'amount' : IDL.Float64,
});
export const DepositStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const DepositRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : DepositStatus,
  'screenshotBlobId' : IDL.Text,
  'note' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
  'user' : IDL.Principal,
  'amount' : IDL.Float64,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'transactionType' : IDL.Variant({
    'withdrawalRequest' : WithdrawalRequest,
    'depositRequest' : DepositRequest,
  }),
  'createdAt' : IDL.Int,
  'amount' : IDL.Float64,
});
export const BankAccount = IDL.Record({
  'id' : IDL.Nat,
  'ifscCode' : IDL.Text,
  'createdAt' : IDL.Int,
  'user' : IDL.Principal,
  'accountName' : IDL.Text,
  'accountNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBankAccount' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'creditCommission' : IDL.Func([IDL.Principal, IDL.Float64], [], []),
  'deleteBankAccount' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommissionBalance' : IDL.Func([], [IDL.Float64], ['query']),
  'getTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listBankAccounts' : IDL.Func([], [IDL.Vec(BankAccount)], ['query']),
  'listDeposits' : IDL.Func([], [IDL.Vec(DepositRequest)], ['query']),
  'listWithdrawals' : IDL.Func([], [IDL.Vec(WithdrawalRequest)], ['query']),
  'register' : IDL.Func([Phone, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitDeposit' : IDL.Func(
      [IDL.Float64, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'submitWithdrawal' : IDL.Func([IDL.Float64, IDL.Nat], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Phone = IDL.Text;
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'phone' : Phone,
  });
  const WithdrawalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const WithdrawalRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : WithdrawalStatus,
    'bankAccountId' : IDL.Nat,
    'createdAt' : IDL.Int,
    'user' : IDL.Principal,
    'amount' : IDL.Float64,
  });
  const DepositStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const DepositRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : DepositStatus,
    'screenshotBlobId' : IDL.Text,
    'note' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
    'user' : IDL.Principal,
    'amount' : IDL.Float64,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'transactionType' : IDL.Variant({
      'withdrawalRequest' : WithdrawalRequest,
      'depositRequest' : DepositRequest,
    }),
    'createdAt' : IDL.Int,
    'amount' : IDL.Float64,
  });
  const BankAccount = IDL.Record({
    'id' : IDL.Nat,
    'ifscCode' : IDL.Text,
    'createdAt' : IDL.Int,
    'user' : IDL.Principal,
    'accountName' : IDL.Text,
    'accountNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBankAccount' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'creditCommission' : IDL.Func([IDL.Principal, IDL.Float64], [], []),
    'deleteBankAccount' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommissionBalance' : IDL.Func([], [IDL.Float64], ['query']),
    'getTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listBankAccounts' : IDL.Func([], [IDL.Vec(BankAccount)], ['query']),
    'listDeposits' : IDL.Func([], [IDL.Vec(DepositRequest)], ['query']),
    'listWithdrawals' : IDL.Func([], [IDL.Vec(WithdrawalRequest)], ['query']),
    'register' : IDL.Func([Phone, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitDeposit' : IDL.Func(
        [IDL.Float64, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'submitWithdrawal' : IDL.Func([IDL.Float64, IDL.Nat], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };