/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BankAccount {
  'id' : bigint,
  'ifscCode' : string,
  'createdAt' : bigint,
  'user' : Principal,
  'accountName' : string,
  'accountNumber' : string,
}
export interface DepositRequest {
  'id' : bigint,
  'status' : DepositStatus,
  'screenshotBlobId' : string,
  'note' : [] | [string],
  'createdAt' : bigint,
  'user' : Principal,
  'amount' : number,
}
export type DepositStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type Phone = string;
export interface Transaction {
  'id' : bigint,
  'transactionType' : { 'withdrawalRequest' : WithdrawalRequest } |
    { 'depositRequest' : DepositRequest },
  'createdAt' : bigint,
  'amount' : number,
}
export interface UserProfile {
  'principal' : Principal,
  'name' : string,
  'phone' : Phone,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WithdrawalRequest {
  'id' : bigint,
  'status' : WithdrawalStatus,
  'bankAccountId' : bigint,
  'createdAt' : bigint,
  'user' : Principal,
  'amount' : number,
}
export type WithdrawalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBankAccount' : ActorMethod<[string, string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'creditCommission' : ActorMethod<[Principal, number], undefined>,
  'deleteBankAccount' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], UserProfile>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommissionBalance' : ActorMethod<[], number>,
  'getTransactionHistory' : ActorMethod<[], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], UserProfile>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listBankAccounts' : ActorMethod<[], Array<BankAccount>>,
  'listDeposits' : ActorMethod<[], Array<DepositRequest>>,
  'listWithdrawals' : ActorMethod<[], Array<WithdrawalRequest>>,
  'register' : ActorMethod<[Phone, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitDeposit' : ActorMethod<[number, string, [] | [string]], bigint>,
  'submitWithdrawal' : ActorMethod<[number, bigint], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];